### ISSUE TITLE
这算bug 吗?

### ISSUE THREAD

**Issue by iYoullloveGitHub** [wanglu1209/PhotoViewer#10]
![screenshot_20181130-152605](https://user-images.githubusercontent.com/23657712/49275040-0e3df700-f4b5-11e8-8e62-0c6fdf26476d.jpg)

**Comment by wanglu1209** [comment]
咋了这是

**Comment by iYoullloveGitHub** [comment]
点击关闭的时候,多点触控,100% 引起

**Comment by wanglu1209** [comment]
是点击的时候马上多个手指点上去吗，还是怎么样的操作。
可否具体说一下，我这边不是很清楚到底是怎么操作的

**Comment by wanglu1209** [comment]
ok，问题收到，会尽快解决
