### ISSUE TITLE
小小咨询

### ISSUE THREAD

**Issue by as11051105** [wanglu1209/PhotoViewer#12]
必须要传容器进去？比如我点击按钮查询接口返回显示一张或多张Url，只有 ArrayList<String> mUrls，没有imageview，ListView和RecyclerView， 这怎么实现呢？

**Comment by wanglu1209** [comment]
没有容器？那页面是怎么展现的

**Comment by as11051105** [comment]
页面上就一个按钮，点击按钮通过查询接口返回图片一张或多张的Url，相当于默认不显示， 需要查看时才去点击查看大图

**Comment by wanglu1209** [comment]
加我qq2021765485，不是很明白你的需求
