### ISSUE TITLE
0.48版本发布失败了，Report状态

### ISSUE THREAD

**Issue by hi4t** [wanglu1209/PhotoViewer#13]
Gradle版本太低了

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
   > Minimum supported Gradle version is 4.6. Current version is 4.1. If using the gradle wrapper, try editing the distributionUrl in /home/jitpack/build/gradle/wrapper/gradle-wrapper.properties to gradle-4.6-all.zip

**Comment by wanglu1209** [comment]
请升级一下你的Gradle版本

distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip

**Comment by zaceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee** [comment]
> 请升级一下你的Gradle版本
> 
> distributionUrl=https://services.gradle.org/distributions/gradle-4.6-all.zip

不是我的，是你的，你的插件发布失败了，你去jitpack看下。。

**Comment by wanglu1209** [comment]
哦哦哦，我看看

**Comment by wanglu1209** [comment]
0.49应该ok了
