### ISSUE TITLE
使用0.47版本报错

### ISSUE THREAD

**Issue by 874355274** [wanglu1209/PhotoViewer#16]
java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/com.bear.maker.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.bear.maker.demo-1/lib/arm64, /vendor/lib64, /system/lib64]]

**Comment by wanglu1209** [comment]
你的项目支持kotlin不？

可以试试在build.gradle里添加 apply plugin:'kotlin-android'

**Comment by wanglu1209** [comment]
我这里新建项目导入0.47没问题啊

**Comment by wanglu1209** [comment]
运行也没问题

**Comment by 874355274** [comment]
![image](https://user-images.githubusercontent.com/26811743/49720224-30e0c480-fc9a-11e8-8c5a-046afa0e5187.png)

我这个调用是否有错误

**Comment by wanglu1209** [comment]
没问题

**Comment by wanglu1209** [comment]
![image](https://user-images.githubusercontent.com/17212822/49721118-7605f600-fc9c-11e8-9f45-15e64e4d7a0b.png)

我新建的项目，用Java写的，没毛病啊

**Comment by wanglu1209** [comment]
请问是否还有问题？

**Comment by 874355274** [comment]
没有了，谢谢
