### ISSUE TITLE
start后不可FragmentActivity类型的

### ISSUE THREAD

**Issue by yun58** [wanglu1209/PhotoViewer#17]

**Comment by wanglu1209** [comment]
最新版本已经支持到了androidx，以前support版本将不会受到支持了。
所以如果要用的话，请将自己项目升级到androidx的版本

**Comment by REBOOTERS** [comment]
话说国内应用适配到 androidx  的应该不多吧，不考虑兼容一下 v4 的 Fragment 吗？ 毕竟这才是使用最多的 Fragment 呀 😳😳
