### ISSUE TITLE
请问集成的photoview的版本是多少啊

### ISSUE THREAD

**Issue by jasonSuzhow** [wanglu1209/PhotoViewer#18]

**Comment by jasonSuzhow** [comment]
额, 是chrisbanes的PhotoView的版本,  还有一个问题就是, 如果这个不是Androidx 的AppCompatActivity 是不是就不行啊. 
![image](https://user-images.githubusercontent.com/13963143/50439317-8d93de80-092c-11e9-99bf-d1522bb6a9fa.png)  麻烦大佬了

**Comment by wanglu1209** [comment]
对，如果不是androidx的就不行，
PhotoView的版本不记得了，时间挺久了

**Comment by jasonSuzhow** [comment]
好的
