### ISSUE TITLE
Android非kotlin工程使用报错

### ISSUE THREAD

**Issue by kylin17** [wanglu1209/PhotoViewer#2]
本人对kotlin不熟，普通Android工程使用报错，如图，会提示找不到静态方法：
![image](https://user-images.githubusercontent.com/1879771/47405773-be696300-d785-11e8-9ce9-8a77f4d0e0e9.png)

**Comment by wanglu1209** [comment]
使用 PhotoViewer.INSTANCE.setData

**Comment by kylin17** [comment]
Got it, Thanks!
