### ISSUE TITLE
优秀项目！

### ISSUE THREAD

**Issue by GuoLiangjun123** [wanglu1209/PhotoViewer#20]
请问java的安卓可以集成这个库吗 我看全是kt写的

**Comment by wanglu1209** [comment]
可以，需要注意的是在调用方法时使用 PhotoViewer.INSTANCE.XXX(方法名)

**Comment by GuoLiangjun123** [comment]
> 可以，需要注意的是在调用方法时使用 PhotoViewer.INSTANCE.XXX(方法名)
前辈 可以加个QQ嘛.....我加你了已经...有些问题还是不懂

**Comment by IdioticMadman** [comment]
@wanglu1209 可以加个@JvmStatic的注解，就可以不用谢INSTANCE了
