### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by CTSN** [wanglu1209/PhotoViewer#3]
![wechatimg178](https://user-images.githubusercontent.com/20452719/47553455-be11c900-d939-11e8-97cb-1eaffed0f0c1.png)

**Comment by wanglu1209** [comment]
收到，谢谢。周末看一下

**Comment by wanglu1209** [comment]
发布新版本0.35，我这边测试解决了内存泄露的问题，请试一下
