### ISSUE TITLE
发现一个闪退问题

### ISSUE THREAD

**Issue by CTSN** [wanglu1209/PhotoViewer#4]
![07951345-ca28-41f9-8e1a-4cdb734efeab](https://user-images.githubusercontent.com/20452719/47635942-a896dc00-db91-11e8-923d-3c919e148ed7.png)

**Comment by CTSN** [comment]
0.35版本

**Comment by wanglu1209** [comment]
不好意思，没有看到。0.36版本增加了判空处理
