### ISSUE TITLE
浏览图片的时候可以加长按保存或者其他保存方式的回调嘛

### ISSUE THREAD

**Issue by 932707629** [wanglu1209/PhotoViewer#6]

**Comment by 932707629** [comment]
在show(ImageView imageView, String s)方法里面对imageview设置长按监听可以实现长按保存

**Comment by wanglu1209** [comment]
问题已经解决，增加了接口回调，请更新到0.40

.setOnLongClickListener(object : OnLongClickListener{
                        override fun onLongClick(view: View) {
                            Toast.makeText(view.context, "haha", Toast.LENGTH_LONG).show()
                        }
                    })
