### ISSUE TITLE
用java调用 闪退 

### ISSUE THREAD

**Issue by SilasDong** [wanglu1209/PhotoViewer#7]
//调用代码
```java
PhotoViewer.INSTANCE.setData(StringUtils.str2List(getUrls(list))).setCurrentPage(holder.getLayoutPosition()).setImgContainer(mRecyclerView).setShowImageViewInterface((iv, url)->{
                            GlideRadiusLoader.displayImage(SuggestionsActivity.this, url, iv);
                        }).start(SuggestionsActivity.this);
```

// 报错信息
11-23 17:36:03.357 18098-18389/com.bk.spay E/AndroidRuntime: FATAL EXCEPTION: Timer-5
    Process: com.bk.spay, PID: 18098
    java.lang.IllegalStateException: Fragment already active
        at android.support.v4.app.Fragment.setArguments(Fragment.java:558)
        at com.wanglu.photoviewerlibrary.PhotoViewer$show$2$onPageSelected$$inlined$timerTask$1.run(Timer.kt:150)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
11-23 17:36:03.690 1567-2099/? E/NetdConnector: RCV <- {613 IfaceClass active 1 534893639889538 10209}
11-23 17:36:03.930 1067-1067/? E/wificond: vivo add tx_good 1109655 tx_bad 862 rx_good 3385782 tx_retry 163672
11-23 17:36:04.436 18098-18389/com.bk.spay E/CrashHandler: In thread: Thread[Timer-5,5,main]
    UncaughtException detected: java.lang.IllegalStateException: Fragment already active
        at android.support.v4.app.Fragment.setArguments(Fragment.java:558)
        at com.wanglu.photoviewerlibrary.PhotoViewer$show$2$onPageSelected$$inlined$timerTask$1.run(Timer.kt:150)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

====
我把PhotoViewer中的fragments的赋值注释了就可以了，这个是什么情况
```java
 // 这里延时0.2s是为了解决上面👆的问题。因为如果刚调用ScrollToPosition方法，就获取itemView是获取不到的，所以要延时一下
                Timer().schedule(timerTask {
                    val b = Bundle()
                    b.putString("pic_data", imgData[currentPage])
                    b.putIntArray("img_size", intArrayOf(getItemView().measuredWidth, getItemView().measuredHeight))
                    b.putBoolean("in_anim", false)
                    b.putIntArray("exit_location", getCurrentViewLocation())
//                    fragments[position].arguments = b
                }, 200)
```

**Comment by wanglu1209** [comment]
已经更新到0.43

不能删除给fragment赋值的代码

**Comment by SilasDong** [comment]
修改了代码  还有会闪退  报一样的错误

**Comment by wanglu1209** [comment]
老铁 0.44试一下。我改了传参的方式，不用setArguments了

**Comment by wanglu1209** [comment]
可以加我QQ 2021765485

**Comment by SilasDong** [comment]
可以了
